# MegaLinter configuration file

enabled_linters:
  - PHP_PHPCS             # PHP Code Sniffer per PHP
  - CSS_STYLELINT         # Stylelint per CSS
  - HTML_HTMLHINT         # HTMLHint per HTML
  - JAVASCRIPT_ESLINT     # ESLint per JavaScript

# Directory to lint
directories:
  - Documenti
  - TestFolder

# Excluded files
exclusions:
  - src/generated/*

# Configurazione di MegaLinter
disable_linters:
  - REPOSITORY_CHECKOV   # Disabilita Checkov
  - REPOSITORY_KICS      # Disabilita KICS

linters_settings:
  PHP_PHPCS:
    rules: PSR12           # Segui lo standard PSR12
  SPELL_CSPELL:
    config: cspell.json    # Usa una whitelist per parole personalizzate

DISABLE_GITHUB_ACTIONS_API: true  # Evita errori di connessione alle API
