name: MegaLinter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run MegaLinter
        uses: oxsecurity/megalinter@v8.3.0
        env:
          GITHUB_TOKEN: ${{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}}
